### ISSUE TITLE
Line 60 - The name and the comments for the function can be improved to describe the functionality better.

### ISSUE THREAD

**Issue by SteveEaston** [SteveEaston/expertiza#6]

**Comment by yagmurbbayraktar** [comment]
- Lots of comments added to explain individual uses of the blocks of codes.
- valid boolean is turned to valid_flag in order to emphasize it is a flag for checking validity of the answer
- questionnaire has been refactored into quiz emphasize it's usage in the program.
- ques_type is refactored into question_type for extra clarify
- new_score is refactored into each_answer_score to clarify its specific usage
